Fix Parent directory of model.ckpt doesn't exis
ValueError: Parent directory of model.ckpt doesn't exist, can't 
save_path = saver.save(sess, "model.ckpt") to save_path = saver.save(sess, "./model.ckpt")